#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import random
import duckdb


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description='Convert Cosmopedia parquet shards to curated markdown corpus.')
    p.add_argument('--input-glob', default='training_data/train-*.parquet', help='Glob for parquet shards')
    p.add_argument('--output', default='training_data/cosmopedia_curated_v1.md', help='Output markdown path')
    p.add_argument('--max-stories', type=int, default=100_000, help='Maximum stories to export')
    p.add_argument('--max-bytes', type=int, default=200 * 1024 * 1024, help='Byte budget for output file')
    p.add_argument('--min-chars', type=int, default=300, help='Drop stories shorter than this')
    p.add_argument('--max-chars', type=int, default=6000, help='Drop stories longer than this')
    p.add_argument('--include-meta', action='store_true', help='Include format/audience/seed metadata headers')
    p.add_argument(
        '--sample-mode',
        choices=('first_fit', 'reservoir'),
        default='first_fit',
        help='first_fit stops when budget is full; reservoir samples uniformly from all shards',
    )
    p.add_argument('--seed', type=int, default=1337, help='Random seed for reservoir mode')
    return p.parse_args()


def iter_rows(con: duckdb.DuckDBPyConnection, shard: Path):
    q = (
        "SELECT text, format, audience, seed_data "
        f"FROM read_parquet('{shard.as_posix()}') "
        "WHERE text IS NOT NULL"
    )
    cur = con.execute(q)
    while True:
        rows = cur.fetchmany(2048)
        if not rows:
            break
        for row in rows:
            yield row


def main() -> None:
    args = parse_args()
    shards = sorted(Path('.').glob(args.input_glob))
    if not shards:
        raise FileNotFoundError(f'No parquet shards found for glob: {args.input_glob}')

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    con = duckdb.connect()

    written = 0
    scanned = 0
    skipped_short = 0
    skipped_long = 0
    current_bytes = 0
    reservoir = []
    rng = random.Random(args.seed)

    def format_block(idx: int, text: str, fmt: str, audience: str, seed_data: str) -> str:
        block = [f'## Story {idx}']
        if args.include_meta:
            block.append(f'- format: `{fmt}`')
            block.append(f'- audience: `{audience}`')
            block.append(f'- seed_data: `{seed_data}`')
        block.append('')
        block.append(text)
        block.append('')
        block.append('---')
        block.append('')
        return '\n'.join(block)

    def add_candidate(text: str, fmt: str, audience: str, seed_data: str) -> None:
        nonlocal scanned
        scanned += 1
        if args.sample_mode == 'reservoir':
            if len(reservoir) < args.max_stories:
                reservoir.append((text, fmt, audience, seed_data))
            else:
                j = rng.randint(0, scanned - 1)
                if j < args.max_stories:
                    reservoir[j] = (text, fmt, audience, seed_data)
        else:
            reservoir.append((text, fmt, audience, seed_data))

    with out_path.open('w', encoding='utf-8') as f:
        f.write('# Cosmopedia Curated v1\n\n')
        f.write('<!-- generated by workflow/convert_cosmopedia_to_md.py -->\n\n')
        current_bytes = out_path.stat().st_size

        for shard in shards:
            for text, fmt, audience, seed_data in iter_rows(con, shard):
                if args.sample_mode == 'first_fit' and (
                    written >= args.max_stories or current_bytes >= args.max_bytes
                ):
                    break

                if text is None:
                    continue
                t = ' '.join(str(text).split())
                n = len(t)
                if n < args.min_chars:
                    skipped_short += 1
                    continue
                if n > args.max_chars:
                    skipped_long += 1
                    continue

                add_candidate(t, str(fmt), str(audience), str(seed_data))

                if args.sample_mode == 'first_fit':
                    payload = format_block(written + 1, t, str(fmt), str(audience), str(seed_data))
                    payload_bytes = len(payload.encode('utf-8'))
                    if current_bytes + payload_bytes > args.max_bytes:
                        break
                    f.write(payload)
                    written += 1
                    current_bytes += payload_bytes

            if args.sample_mode == 'first_fit' and (
                written >= args.max_stories or current_bytes >= args.max_bytes
            ):
                break

        if args.sample_mode == 'reservoir':
            for text, fmt, audience, seed_data in reservoir:
                payload = format_block(written + 1, text, fmt, audience, seed_data)
                payload_bytes = len(payload.encode('utf-8'))
                if current_bytes + payload_bytes > args.max_bytes:
                    break
                f.write(payload)
                written += 1
                current_bytes += payload_bytes

    print('output:', out_path)
    print('stories_written:', written)
    print('stories_scanned:', scanned)
    print('bytes:', current_bytes)
    print('skipped_short:', skipped_short)
    print('skipped_long:', skipped_long)
    print('shards_seen:', len(shards))


if __name__ == '__main__':
    main()
