"""Reconcile Campaign 36's accepted base corpus with reviewed generated images.

The report is deterministic and read-only with respect to source ledgers.  It maps each
accepted Flux/ImageGen assignment back to the exact missing curriculum slots planned for
its concepts, verifies bytes and hashes, and reports the genuine residual generation gap.
"""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
import json
from pathlib import Path
from typing import Any

from image_registry.campaign36_flux_streaming_luna import digest, load_jsonl
from image_registry.campaign36_imagegen_fallback import DEFAULT_ROOT


DEFAULT_CAMPAIGN_ROOT = DEFAULT_ROOT.parent
SCHEMA_VERSION = "ninereeds_campaign36_visual_reconciliation_v1"


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.write_text(
        "".join(json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n" for row in rows),
        encoding="utf-8",
    )


def accepted_generated(root: Path) -> dict[str, dict[str, Any]]:
    accepted: dict[str, dict[str, Any]] = {}
    for provider, path in (
        ("flux", root / "streaming-luna" / "decisions.jsonl"),
        ("codex-imagegen", root / "imagegen-v1" / "decisions.jsonl"),
        ("policy-recovery", root / "imagegen-v1" / "policy-recoveries.jsonl"),
    ):
        for row in load_jsonl(path, tolerate_partial_tail=True):
            if row.get("verdict") != "accepted":
                continue
            assignment = str(row["assignment_id"])
            candidate = {**row, "accepted_provider": provider}
            # Later policy recovery is authoritative for its previously unresolved
            # assignment; otherwise preserve the first accepted immutable asset.
            if assignment not in accepted or provider == "policy-recovery":
                accepted[assignment] = candidate
    return accepted


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--campaign-root", type=Path, default=DEFAULT_CAMPAIGN_ROOT)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    campaign = args.campaign_root
    flux = campaign / "flux-specialist-v1"
    output = args.output or flux / "reconciliation-current"
    output.mkdir(parents=True, exist_ok=True)

    state = json.loads((campaign / "loop" / "state.json").read_text(encoding="utf-8"))
    base_path = Path(state["authoritative_decisions"])
    base = load_jsonl(base_path)
    if len(base) != 25_000 or len({row["slot_id"] for row in base}) != 25_000:
        raise ValueError("authoritative base is not the exact 25,000-slot contract")
    inventory_rows = load_jsonl(flux / "inventory" / "gap_inventory.jsonl")
    inventory = {row["concept_id"]: row for row in inventory_rows}
    briefs = load_jsonl(flux / "prompt-composition" / "production_briefs.jsonl")

    planned: dict[str, list[tuple[str, int]]] = defaultdict(list)
    claims: dict[str, list[str]] = {}
    for brief in briefs:
        brief_id = str(brief["production_brief_id"])
        ids = list(brief["concept_ids"])
        for variant in range(int(brief["variant_count"])):
            assignment = f"{brief_id}-v{variant:02d}"
            claims[assignment] = ids
            for concept_id in ids:
                planned[concept_id].append((assignment, variant))

    slot_for: dict[tuple[str, str], str] = {}
    for concept_id, occurrences in planned.items():
        missing = list(inventory[concept_id]["missing_slot_ids"])
        if len(occurrences) != len(missing):
            raise ValueError(
                f"planned occurrence/slot mismatch for {concept_id}: "
                f"{len(occurrences)} != {len(missing)}"
            )
        for (assignment, _variant), slot_id in zip(occurrences, missing, strict=True):
            slot_for[(assignment, concept_id)] = slot_id

    accepted = accepted_generated(flux)
    unknown = set(accepted) - set(claims)
    if unknown:
        raise ValueError(f"accepted generated assignments outside frozen plan: {sorted(unknown)[:5]}")

    generated_slots: list[dict[str, Any]] = []
    hashes: Counter[str] = Counter()
    providers: Counter[str] = Counter()
    for assignment, row in sorted(accepted.items()):
        path = Path(str(row.get("local_path", "")))
        expected = str(row.get("sha256", ""))
        if not path.is_file() or not expected or digest(path) != expected:
            raise ValueError(f"accepted generated bytes fail validation: {assignment}")
        hashes[expected] += 1
        providers[row["accepted_provider"]] += 1
        for concept_id in claims[assignment]:
            generated_slots.append({
                "schema_version": SCHEMA_VERSION,
                "slot_id": slot_for[(assignment, concept_id)],
                "concept_id": concept_id,
                "word": inventory[concept_id]["word"],
                "assignment_id": assignment,
                "asset_sha256": expected,
                "local_path": str(path),
                "accepted_provider": row["accepted_provider"],
                "literal_caption": (row.get("luna_result") or {}).get("literal_caption"),
                "target_evidence": next((
                    target.get("evidence")
                    for target in (row.get("luna_result") or {}).get("targets", [])
                    if target.get("concept_id") == concept_id
                ), None),
            })

    accepted_base = [row for row in base if row.get("disposition") == "accepted"]
    generated_slot_ids = {row["slot_id"] for row in generated_slots}
    base_slot_ids = {row["slot_id"] for row in accepted_base}
    if generated_slot_ids & base_slot_ids:
        raise ValueError("generated material overlaps an already accepted base slot")

    pending_assignments = sorted(set(claims) - set(accepted))
    pending_slots = [
        {
            "assignment_id": assignment,
            "concept_id": concept_id,
            "slot_id": slot_for[(assignment, concept_id)],
            "word": inventory[concept_id]["word"],
        }
        for assignment in pending_assignments
        for concept_id in claims[assignment]
    ]
    accepted_by_concept = Counter(row["concept_id"] for row in accepted_base)
    accepted_by_concept.update(row["concept_id"] for row in generated_slots)
    concept_coverage = []
    for concept_id, rows in sorted(
        ((key, [row for row in base if row["concept_id"] == key]) for key in {r["concept_id"] for r in base}),
        key=lambda item: int(item[1][0]["ordinal"]),
    ):
        count = accepted_by_concept[concept_id]
        concept_coverage.append({
            "concept_id": concept_id,
            "word": rows[0]["word"],
            "ordinal": rows[0]["ordinal"],
            "accepted_image_slots": count,
            "required_slots": 10,
            "still_image_gap": max(0, 10 - count),
            "residual_route": inventory.get(concept_id, {}).get("route", "accepted_images"),
        })

    duplicate_hashes = {key: value for key, value in hashes.items() if value > 1}
    report = {
        "schema_version": SCHEMA_VERSION,
        "status": "reconciliation_in_progress" if pending_assignments else "still_image_plan_complete",
        "contract_slots": 25_000,
        "base_accepted_slots": len(accepted_base),
        "generated_plan_assignments": len(claims),
        "generated_plan_slots": len(slot_for),
        "accepted_generated_assignments": len(accepted),
        "accepted_generated_slots": len(generated_slots),
        "current_accepted_image_slots": len(accepted_base) + len(generated_slots),
        "pending_generated_assignments": len(pending_assignments),
        "pending_generated_slots": len(pending_slots),
        "accepted_assignment_providers": dict(sorted(providers.items())),
        "pixel_duplicate_generated_hashes": len(duplicate_hashes),
        "concepts_at_ten_images": sum(row["accepted_image_slots"] == 10 for row in concept_coverage),
        "concepts_below_ten_images": sum(row["accepted_image_slots"] < 10 for row in concept_coverage),
        "authoritative_base": str(base_path),
    }
    write_jsonl(output / "accepted-generated-slots.jsonl", generated_slots)
    write_jsonl(output / "pending-generated-slots.jsonl", pending_slots)
    write_jsonl(output / "concept-coverage.jsonl", concept_coverage)
    (output / "summary.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
